spring:
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true

##After an interval of 3s the message should be retried.
          initial-interval: 3s

##Maximum 6 times the message should be retried.
##It is then sent to the dead letter Queue.
          max-attempts: 6

##The maximum interval should not be more than 10s between two retries.
          max-interval: 10s

##The gap is multiplied by 2 between second repetition.
## But the maximum interval can never be exceeded
          multiplier: 2
##So the retry interval values will be 3s, 6s, 10s, 10s, 10s. As 10 sec is the max interval specified.
         
server:
  port: 8081
